# Generated by Django 5.1 on 2024-09-02 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('atencion', 'En Atención'), ('observacion', 'En Observación'), ('espera_atencion', 'En Espera de Atención'), ('espera_triage', 'En Espera de Triage'), ('hospitalizado', 'Hospitalizados'), ('cirugia', 'En Cirugía'), ('uci', 'En UCI')], max_length=20)),
            ],
        ),
    ]
