# Generated by Django 5.1 on 2024-09-02 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='documento',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
