# Generated by Django 5.1 on 2024-09-02 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('sexo', models.CharField(choices=[('hombre', 'Masculino'), ('mujer', 'Femenino'), ('otro', 'Otro'), ('espera_triage', 'En Espera de Triage')], max_length=20)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('motivo_ingreso', models.TextField()),
                ('diagnostico_inicial', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_salida', models.DateTimeField(blank=True, null=True)),
                ('motivo_salida', models.CharField(blank=True, max_length=255, null=True)),
                ('alta_medica', models.BooleanField(default=False)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historias_clinicas', to='admision.pacientes')),
            ],
        ),
    ]
